### ISSUE TITLE
Tracker: Migrate from in-repo mill plugin to external project

### ISSUE THREAD

**Issue by lefou** [scala-steward-org/scala-steward#2818]
Here is the plan:

* [x] Migrate the code of the mill-plugin to a separate repository, see also #2704 
 * Done: https://github.com/scala-steward-org/mill-plugin
* [x] Decide an a version scheme for external mill-plugin and make a first release
 * Done: first release version: `0.17.0`
* [x] Refactor scala-steward code to use the new external plugin
 * PR: https://github.com/scala-steward-org/scala-steward/pull/2821
 * PR: https://github.com/scala-steward-org/scala-steward/pull/2823
* [x] Remove mill-plugin module from this project
* [x] ~Update documentation~ (there is none affected)

**Comment by fthomas** [comment]
This plan looks good to me.

> Decide an a version scheme for external mill-plugin and make a first release

What kind of version scheme do you have in mind? I would probably just start with a 0.0.1 or 0.1.0 and check if it is working here.

**Comment by lefou** [comment]
> This plan looks good to me.
> 
> > Decide an a version scheme for external mill-plugin and make a first release
> 
> What kind of version scheme do you have in mind? I would probably just start with a 0.0.1 or 0.1.0 and check if it is working here.

I'd rather avoid any version collisions or confusion with previously released versions of this plugin (as part of scala-steward releases). Scala Steward is currently on `0.16.x`, so maybe we can start with `0.17.0` or something like that.

**Comment by fthomas** [comment]
> I'd rather avoid any version collisions or confusion with previously released versions of this plugin (as part of scala-steward releases). Scala Steward is currently on `0.16.x`, so maybe we can start with `0.17.0` or something like that.

Good point. I forgot that we already release the mill-plugin that is in this repo: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/ :-)

0.17.0 sounds good to me. Does the new plugin will have the same artifactId as the old one?

**Comment by lefou** [comment]
> > I'd rather avoid any version collisions or confusion with previously released versions of this plugin (as part of scala-steward releases). Scala Steward is currently on `0.16.x`, so maybe we can start with `0.17.0` or something like that.
> 
> Good point. I forgot that we already release the mill-plugin that is in this repo: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/ :-)
> 
> 0.17.0 sounds good to me. Does the new plugin will have the same artifactId as the old one?

In principle yes. (Currently, it's `mill-scala-steward`, but I'm going to change that.) But the final `artifactId` will also contain the Mill platform. E.g. the full GAV for Mill 0.10 version will eventually look like this: `org.scala-steward:scala-steward-mill-plugin_mill0.10_2.13:0.17.0`

**Comment by lefou** [comment]
Is there any documentation that needs change or additions?

**Comment by fthomas** [comment]
I'm not aware of any existing documentation that needs to be updated.

**Comment by lefou** [comment]
Thank. I think this is completed now. Thank you all!

**Comment by fthomas** [comment]
Many thanks @lefou for working on this!

**Comment by fthomas** [comment]
I guess it would be nice to release this soon. @scala-steward-org/core any objections against publishing current `main` as  0.17.0?

**Comment by fthomas** [comment]
0.17.0 has just been released.
