### ISSUE TITLE
[meta] Prospective Scalafix migrations

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#655]
This is a meta issue for collecting and keeping track of prospective Scalafix migrations that could be added to Scala Steward.

* [ ] ZIO 2.0: https://github.com/zio/zio/issues/5779
* [x] Cats Effect 3.3.0: https://github.com/typelevel/cats-effect/pull/2343 (added in #2270)
* [ ] ~http4s 0.22: https://github.com/http4s/http4s/pull/4611~
* [x] Cats Effect 3.0.0: https://github.com/typelevel/cats-effect/issues/1049 (added in #1940)
* [x] Cats 2.2.0: https://github.com/typelevel/cats/issues/3563 (added in #1588)
* [x] http4s 0.21.5: https://github.com/http4s/http4s/pull/3372 (added in #1510)
* [ ] ~https://github.com/functional-streams-for-scala/fs2/issues/1511~
* [ ] ~https://github.com/typelevel/kind-projector/issues/108#issuecomment-507818067~
* [ ] https://github.com/julien-truffaut/Monocle/issues/684
* [ ] https://github.com/playframework/playframework/issues/9448
* [x] https://github.com/typelevel/scalacheck/pull/498 (added in #853)
* [x] https://github.com/scalatest/scalatest/issues/1657

**Comment by cquiroz** [comment]
In the case of monocle the name of the package may go form `monocle-cats` to plain `monocle`. Can a migration be done for that case?

**Comment by fthomas** [comment]
@cquiroz If a project depends only on `monocle-cats` and that there won't be a `monocle-cats` 2.0 because all of its functionality is in `monocle` now, Scala Steward won't even attempt to update it. I think it would make people's life easier if you'd provide an empty `monocle-cats` 2.0 that just depends on `monocle`. In this case Scala Steward would update the version and run the Scalafix migration.

**Comment by exoego** [comment]
Ref: https://github.com/fthomas/scala-steward/issues/771

If this issue #65 is a meta issue, I think this should be pinned so that users add more prospective Scalafix migrations

**Comment by smarter** [comment]
PR for the scalacheck migration: https://github.com/fthomas/scala-steward/pull/853

**Comment by fthomas** [comment]
The original post has been last edited two years ago. It serves no purpose anymore and it is time to close this issue.
